### PR TITLE
Add Atlanta to the list of Hometowns

### PR DESCRIPTION
**Pull request by bchalamayya**
- Has anyone into Atlanta befire? If so, What did I iss?
- @githubteacher  did I list enough things for kids to do?
- Do you care more about what the locals think, Or do you want tourist stuff?

### CODE REVIEW

**Comment by smitley** [comment]
I have never been to Atlanta!

**Comment by maureenkelly** [comment]
I hear the Atlanta zoo is nice.  How close is it to the airport?

**Comment by bchalamayya** [comment]
@maureenkelly Its 3min drive from ATL ariport

**Comment by bchalamayya** [comment]
@master-smit You are welcom to Hotlanta

**Pull request merged**
